import os, re
import xml.etree.ElementTree as ET

class Tournament:
    venue_regex = re.compile('.*venues([0-9]+)-main.dat$')
    debate_regex = re.compile('.*debates([0-9]+)-main.xml$')
    team_regex = re.compile('.*teams([0-9]+)-main.xml$')
    judge_regex = re.compile('.*adjudicators([0-9])+-main.xml$')

    def __init__(self):
        self.rounds = dict()
        self.teams = dict()
        self.judges = dict()
        self.venues = dict()

    def sorted_teams(self):
        x = sorted(self.teams.values(), reverse=True, key=lambda t: t.speaks())
        return sorted(x, reverse=True, key=lambda t: t.total())

    def load_zip(self, zip):
        files = [x for x in zip.namelist() if not x.startswith("__MACOSX")] #Strip out files generated by Mac archive process

        venues = [(m.group(1), m.group()) for l in files for m in [self.venue_regex.search(l)] if m]
        rounds = [(m.group(1), m.group()) for l in files for m in [self.debate_regex.search(l)] if m]
        teams = [m.group() for l in files for m in [self.team_regex.search(l)] if m]
        judges = [m.group() for l in files for m in [self.judge_regex.search(l)] if m]

        if not len(rounds):
            print "No files found"
            return

        for i, loc in venues:
            self._read_venue(i, zip.open(loc))

        self._read_judges(zip.open(judges[-1]))
        self._read_teams(zip.open(teams[-1]))

        for i, loc in rounds:
            self._read_round(i, zip.open(loc))

    def load_directory(self, directory):
        files = [x for x in os.listdir(directory)]

        venues = [(m.group(1), m.group()) for l in files for m in [self.venue_regex.search(l)] if m]
        rounds = [(m.group(1), m.group()) for l in files for m in [self.debate_regex.search(l)] if m]
        teams = [m.group() for l in files for m in [self.team_regex.search(l)] if m]
        judges = [m.group() for l in files for m in [self.judge_regex.search(l)] if m]

        if not len(rounds):
            print "No files found"
            return

        for i, loc in venues:
            self._read_venue(i, open(os.path.join(directory, loc)))

        self._read_judges(open(os.path.join(directory, judges[-1])))
        self._read_teams(open(os.path.join(directory, teams[-1])))

        for i, loc in rounds:
            self._read_round(i, open(os.path.join(directory, loc)))

    def _read_venue(self, number, file):
        self.venues[number] = [x.split(" ")[1]  for x in file.readlines()]
        file.close()

    def _read_judges(self, file):
        tree = ET.parse(file)
        file.close()

        judges = [(int(x.get("id")), x.get("name")) for x in tree.getroot().getchildren()]
        for id, name in judges:
            self.judges[id] = Judge(name)

    #TODO look into speakers changing between rounds
    def _read_teams(self, file):
        tree = ET.parse(file)
        file.close()

        for el in tree.findall("team"):
            t = Team(el.get("name"))
            self.teams[int(el.get("ident"))] = t
            home = el.find("home")
            pullups = el.find("pullups")
            if home is not None:
                t.home = home.text
            if pullups is not None:
                t.pullups = pullups
            speakers = [Speaker(x.get("name"), t) for x in el.findall("member")]
            for i, s in enumerate(speakers):
                t.speakers[i] = s

    def _read_round(self, number, file):
        tree = ET.parse(file)
        file.close()
        self.rounds[number] = round = Round(number)

        motion = tree.find("motion")
        judges = tree.find("adjudicators")

        if motion is not None:
            round.motion = motion.text

        for el in tree.findall("debate"):
            vid = int(el.get("venue"))
            round.debates[vid] = debate = Debate(round, self.venues[number][vid])

            for i, tel in enumerate(el.findall("team")):
                t = self.teams[int(tel.get("id"))]
                t.debates[number] = debate
                t.positions[number] = i
                t.scores[number] = int(tel.get("rankpts"))
                debate.positions[i] = t

                for id, points in [(int(x.get("id")), int(x.get("points"))) for x in tel.findall("speaker")]:
                    t.speakers[id].debates[number] = debate
                    t.speakers[id].scores[number] = points

        if judges is not None:
            map = [(int(x.get("adj")), int(x.get("venue"))) for x in judges.getchildren()]
            for j, v in map:
                self.judges[j].debates[number] = round.debates[v]

class Round:
    def __init__(self, number):
        self.number = number
        self.debates = dict()
        self.motion = None

    def __str__(self):
        return "Round %d: %s" % (self.number, self.motion)

class Speaker:
    def __init__(self, name, team):
        self.name = name
        self.team = team
        self.debates = dict()
        self.scores = dict()

    def __str__(self):
        return self.name

    def total(self):
        return sum(self.scores.values())

class Team:
    def __init__(self, name):
        self.name = name
        self.speakers = dict()
        self.debates = dict()
        self.pullups = None
        self.positions = dict()
        self.scores = dict()

    def __str__(self):
        return self.name

    def total(self):
        return sum(self.scores.values())

    def speaks(self):
        return sum([s.total() for s in self.speakers.values()])

class Judge:
    def __init__(self, name):
        self.name = name
        self.debates = dict()

    def __str__(self):
        return self.name

class Debate:
    def __init__(self, round, venue):
        self.round = round
        self.positions = dict()
        self.judges = []
        self.venue = venue